apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloud-native-app.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  APP_ENV: {{ .Values.app.environment | quote }}
  APP_MESSAGE: {{ .Values.app.message | quote }}
