apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-native-app.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  APP_SECRET: {{ .Values.app.secret | quote }}
