apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-native-app
  namespace: cloud-native
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloud-native-app
                port:
                  number: 80
